// Rust test file autogenerated with cargo build (src/build_spectests.rs).
// Please do NOT modify it by hand, as it will be reseted on next build.
// Test based on spectests/call_indirect.wast
use crate::webassembly::{compile, instantiate, Export, ImportObject, ResultObject, VmCtx};
use std::panic;
use wabt::wat2wasm;

// Line 3
fn create_module_1() -> ResultObject {
    let module_str = "(module
      (type (;0;) (func))
      (type (;1;) (func (result i32)))
      (type (;2;) (func (result i64)))
      (type (;3;) (func (result f32)))
      (type (;4;) (func (result f64)))
      (type (;5;) (func (param i32) (result i32)))
      (type (;6;) (func (param i64) (result i64)))
      (type (;7;) (func (param f32) (result f32)))
      (type (;8;) (func (param f64) (result f64)))
      (type (;9;) (func (param f32 i32) (result i32)))
      (type (;10;) (func (param i32 i64) (result i64)))
      (type (;11;) (func (param f64 f32) (result f32)))
      (type (;12;) (func (param i64 f64) (result f64)))
      (type (;13;) (func (param i32) (result i32)))
      (type (;14;) (func (param i64) (result i64)))
      (type (;15;) (func (param f32) (result f32)))
      (type (;16;) (func (param f64) (result f64)))
      (type (;17;) (func (param i64)))
      (type (;18;) (func (param i64 f64 i32 i64)))
      (type (;19;) (func (param i64) (result i32)))
      (type (;20;) (func (param i64 f64 i32 i64) (result i32)))
      (type (;21;) (func (param i32) (result i64)))
      (type (;22;) (func (param i32) (result f32)))
      (type (;23;) (func (param i32) (result f64)))
      (func (;0;) (type 1) (result i32)
        i32.const 306)
      (func (;1;) (type 2) (result i64)
        i64.const 356)
      (func (;2;) (type 3) (result f32)
        f32.const 0x1.e64p+11 (;=3890;))
      (func (;3;) (type 4) (result f64)
        f64.const 0x1.ec8p+11 (;=3940;))
      (func (;4;) (type 5) (param i32) (result i32)
        get_local 0)
      (func (;5;) (type 6) (param i64) (result i64)
        get_local 0)
      (func (;6;) (type 7) (param f32) (result f32)
        get_local 0)
      (func (;7;) (type 8) (param f64) (result f64)
        get_local 0)
      (func (;8;) (type 10) (param i32 i64) (result i64)
        get_local 1)
      (func (;9;) (type 12) (param i64 f64) (result f64)
        get_local 1)
      (func (;10;) (type 9) (param f32 i32) (result i32)
        get_local 1)
      (func (;11;) (type 11) (param f64 f32) (result f32)
        get_local 1)
      (func (;12;) (type 13) (param i32) (result i32)
        get_local 0)
      (func (;13;) (type 14) (param i64) (result i64)
        get_local 0)
      (func (;14;) (type 15) (param f32) (result f32)
        get_local 0)
      (func (;15;) (type 16) (param f64) (result f64)
        get_local 0)
      (func (;16;) (type 0)
        i32.const 0
        call_indirect (type 0)
        i64.const 0
        i32.const 0
        call_indirect (type 17)
        i64.const 0
        f64.const 0x0p+0 (;=0;)
        i32.const 0
        i64.const 0
        i32.const 0
        call_indirect (type 18)
        i32.const 0
        call_indirect (type 0)
        i32.const 0
        call_indirect (type 1)
        i32.eqz
        drop
        i32.const 0
        call_indirect (type 1)
        i32.eqz
        drop
        i64.const 0
        i32.const 0
        call_indirect (type 19)
        i32.eqz
        drop
        i64.const 0
        f64.const 0x0p+0 (;=0;)
        i32.const 0
        i64.const 0
        i32.const 0
        call_indirect (type 20)
        i32.eqz
        drop
        i64.const 0
        i32.const 0
        call_indirect (type 6)
        i64.eqz
        drop)
      (func (;17;) (type 1) (result i32)
        i32.const 0
        call_indirect (type 1))
      (func (;18;) (type 2) (result i64)
        i32.const 1
        call_indirect (type 2))
      (func (;19;) (type 3) (result f32)
        i32.const 2
        call_indirect (type 3))
      (func (;20;) (type 4) (result f64)
        i32.const 3
        call_indirect (type 4))
      (func (;21;) (type 2) (result i64)
        i64.const 100
        i32.const 5
        call_indirect (type 6))
      (func (;22;) (type 1) (result i32)
        i32.const 32
        i32.const 4
        call_indirect (type 5))
      (func (;23;) (type 2) (result i64)
        i64.const 64
        i32.const 5
        call_indirect (type 6))
      (func (;24;) (type 3) (result f32)
        f32.const 0x1.51eb86p+0 (;=1.32;)
        i32.const 6
        call_indirect (type 7))
      (func (;25;) (type 4) (result f64)
        f64.const 0x1.a3d70a3d70a3dp+0 (;=1.64;)
        i32.const 7
        call_indirect (type 8))
      (func (;26;) (type 1) (result i32)
        f32.const 0x1.00ccccp+5 (;=32.1;)
        i32.const 32
        i32.const 8
        call_indirect (type 9))
      (func (;27;) (type 2) (result i64)
        i32.const 32
        i64.const 64
        i32.const 9
        call_indirect (type 10))
      (func (;28;) (type 3) (result f32)
        f64.const 0x1p+6 (;=64;)
        f32.const 0x1p+5 (;=32;)
        i32.const 10
        call_indirect (type 11))
      (func (;29;) (type 4) (result f64)
        i64.const 64
        f64.const 0x1.0066666666666p+6 (;=64.1;)
        i32.const 11
        call_indirect (type 12))
      (func (;30;) (type 10) (param i32 i64) (result i64)
        get_local 1
        get_local 0
        call_indirect (type 6))
      (func (;31;) (type 21) (param i32) (result i64)
        i64.const 9
        get_local 0
        call_indirect (type 14))
      (func (;32;) (type 5) (param i32) (result i32)
        i32.const 9
        get_local 0
        call_indirect (type 13))
      (func (;33;) (type 22) (param i32) (result f32)
        f32.const 0x1.2p+3 (;=9;)
        get_local 0
        call_indirect (type 15))
      (func (;34;) (type 23) (param i32) (result f64)
        f64.const 0x1.2p+3 (;=9;)
        get_local 0
        call_indirect (type 16))
      (func (;35;) (type 6) (param i64) (result i64)
        get_local 0
        i64.eqz
        if (result i64)  ;; label = @1
          i64.const 1
        else
          get_local 0
          get_local 0
          i64.const 1
          i64.sub
          i32.const 12
          call_indirect (type 6)
          i64.mul
        end)
      (func (;36;) (type 6) (param i64) (result i64)
        get_local 0
        i64.const 1
        i64.le_u
        if (result i64)  ;; label = @1
          i64.const 1
        else
          get_local 0
          i64.const 2
          i64.sub
          i32.const 13
          call_indirect (type 6)
          get_local 0
          i64.const 1
          i64.sub
          i32.const 13
          call_indirect (type 6)
          i64.add
        end)
      (func (;37;) (type 5) (param i32) (result i32)
        get_local 0
        i32.eqz
        if (result i32)  ;; label = @1
          i32.const 1
        else
          get_local 0
          get_local 0
          i32.const 1
          i32.sub
          i32.const 23
          call_indirect (type 5)
          i32.mul
        end)
      (func (;38;) (type 7) (param f32) (result f32)
        get_local 0
        f32.const 0x0p+0 (;=0;)
        f32.eq
        if (result f32)  ;; label = @1
          f32.const 0x1p+0 (;=1;)
        else
          get_local 0
          get_local 0
          f32.const 0x1p+0 (;=1;)
          f32.sub
          i32.const 24
          call_indirect (type 7)
          f32.mul
        end)
      (func (;39;) (type 8) (param f64) (result f64)
        get_local 0
        f64.const 0x0p+0 (;=0;)
        f64.eq
        if (result f64)  ;; label = @1
          f64.const 0x1p+0 (;=1;)
        else
          get_local 0
          get_local 0
          f64.const 0x1p+0 (;=1;)
          f64.sub
          i32.const 25
          call_indirect (type 8)
          f64.mul
        end)
      (func (;40;) (type 5) (param i32) (result i32)
        get_local 0
        i32.const 1
        i32.le_u
        if (result i32)  ;; label = @1
          i32.const 1
        else
          get_local 0
          i32.const 2
          i32.sub
          i32.const 26
          call_indirect (type 5)
          get_local 0
          i32.const 1
          i32.sub
          i32.const 26
          call_indirect (type 5)
          i32.add
        end)
      (func (;41;) (type 7) (param f32) (result f32)
        get_local 0
        f32.const 0x1p+0 (;=1;)
        f32.le
        if (result f32)  ;; label = @1
          f32.const 0x1p+0 (;=1;)
        else
          get_local 0
          f32.const 0x1p+1 (;=2;)
          f32.sub
          i32.const 27
          call_indirect (type 7)
          get_local 0
          f32.const 0x1p+0 (;=1;)
          f32.sub
          i32.const 27
          call_indirect (type 7)
          f32.add
        end)
      (func (;42;) (type 8) (param f64) (result f64)
        get_local 0
        f64.const 0x1p+0 (;=1;)
        f64.le
        if (result f64)  ;; label = @1
          f64.const 0x1p+0 (;=1;)
        else
          get_local 0
          f64.const 0x1p+1 (;=2;)
          f64.sub
          i32.const 28
          call_indirect (type 8)
          get_local 0
          f64.const 0x1p+0 (;=1;)
          f64.sub
          i32.const 28
          call_indirect (type 8)
          f64.add
        end)
      (func (;43;) (type 5) (param i32) (result i32)
        get_local 0
        i32.eqz
        if (result i32)  ;; label = @1
          i32.const 44
        else
          get_local 0
          i32.const 1
          i32.sub
          i32.const 15
          call_indirect (type 5)
        end)
      (func (;44;) (type 5) (param i32) (result i32)
        get_local 0
        i32.eqz
        if (result i32)  ;; label = @1
          i32.const 99
        else
          get_local 0
          i32.const 1
          i32.sub
          i32.const 14
          call_indirect (type 5)
        end)
      (func (;45;) (type 0)
        i32.const 16
        call_indirect (type 0))
      (func (;46;) (type 0)
        i32.const 18
        call_indirect (type 0))
      (func (;47;) (type 0)
        i32.const 17
        call_indirect (type 0))
      (func (;48;) (type 1) (result i32)
        i32.const 0
        call_indirect (type 1)
        i32.const 2
        i32.const 3
        select)
      (func (;49;) (type 1) (result i32)
        i32.const 2
        i32.const 0
        call_indirect (type 1)
        i32.const 3
        select)
      (func (;50;) (type 1) (result i32)
        i32.const 2
        i32.const 3
        i32.const 0
        call_indirect (type 1)
        select)
      (func (;51;) (type 1) (result i32)
        i32.const 0
        call_indirect (type 1)
        if (result i32)  ;; label = @1
          i32.const 1
        else
          i32.const 2
        end)
      (func (;52;) (type 2) (result i64)
        block (result i64)  ;; label = @1
          i32.const 1
          call_indirect (type 2)
          i32.const 2
          br_if 0 (;@1;)
        end)
      (func (;53;) (type 1) (result i32)
        block (result i32)  ;; label = @1
          i32.const 2
          i32.const 0
          call_indirect (type 1)
          br_if 0 (;@1;)
        end)
      (func (;54;) (type 3) (result f32)
        block (result f32)  ;; label = @1
          i32.const 2
          call_indirect (type 3)
          i32.const 2
          br_table 0 (;@1;) 0 (;@1;)
        end)
      (func (;55;) (type 1) (result i32)
        block (result i32)  ;; label = @1
          i32.const 2
          i32.const 0
          call_indirect (type 1)
          br_table 0 (;@1;) 0 (;@1;)
        end)
      (func (;56;) (type 0)
        i32.const 0
        call_indirect (type 1)
        i32.const 1
        i32.store)
      (func (;57;) (type 0)
        i32.const 10
        i32.const 3
        call_indirect (type 4)
        f64.store)
      (func (;58;) (type 1) (result i32)
        i32.const 0
        call_indirect (type 1)
        memory.grow)
      (func (;59;) (type 1) (result i32)
        i32.const 1
        i32.const 4
        call_indirect (type 5)
        return)
      (func (;60;) (type 0)
        i64.const 1
        i32.const 5
        call_indirect (type 6)
        drop)
      (func (;61;) (type 3) (result f32)
        block (result f32)  ;; label = @1
          f32.const 0x1p+0 (;=1;)
          i32.const 6
          call_indirect (type 7)
          br 0 (;@1;)
        end)
      (func (;62;) (type 4) (result f64)
        (local f64)
        f64.const 0x1p+0 (;=1;)
        i32.const 7
        call_indirect (type 8)
        set_local 0
        get_local 0)
      (func (;63;) (type 1) (result i32)
        i32.const 0
        call_indirect (type 1)
        i32.load)
      (table (;0;) 29 29 anyfunc)
      (memory (;0;) 1)
      (export \"type-i32\" (func 17))
      (export \"type-i64\" (func 18))
      (export \"type-f32\" (func 19))
      (export \"type-f64\" (func 20))
      (export \"type-index\" (func 21))
      (export \"type-first-i32\" (func 22))
      (export \"type-first-i64\" (func 23))
      (export \"type-first-f32\" (func 24))
      (export \"type-first-f64\" (func 25))
      (export \"type-second-i32\" (func 26))
      (export \"type-second-i64\" (func 27))
      (export \"type-second-f32\" (func 28))
      (export \"type-second-f64\" (func 29))
      (export \"dispatch\" (func 30))
      (export \"dispatch-structural-i64\" (func 31))
      (export \"dispatch-structural-i32\" (func 32))
      (export \"dispatch-structural-f32\" (func 33))
      (export \"dispatch-structural-f64\" (func 34))
      (export \"fac-i64\" (func 35))
      (export \"fib-i64\" (func 36))
      (export \"fac-i32\" (func 37))
      (export \"fac-f32\" (func 38))
      (export \"fac-f64\" (func 39))
      (export \"fib-i32\" (func 40))
      (export \"fib-f32\" (func 41))
      (export \"fib-f64\" (func 42))
      (export \"even\" (func 43))
      (export \"odd\" (func 44))
      (export \"runaway\" (func 45))
      (export \"mutual-runaway\" (func 46))
      (export \"as-select-first\" (func 48))
      (export \"as-select-mid\" (func 49))
      (export \"as-select-last\" (func 50))
      (export \"as-if-condition\" (func 51))
      (export \"as-br_if-first\" (func 52))
      (export \"as-br_if-last\" (func 53))
      (export \"as-br_table-first\" (func 54))
      (export \"as-br_table-last\" (func 55))
      (export \"as-store-first\" (func 56))
      (export \"as-store-last\" (func 57))
      (export \"as-memory.grow-value\" (func 58))
      (export \"as-return-value\" (func 59))
      (export \"as-drop-operand\" (func 60))
      (export \"as-br-value\" (func 61))
      (export \"as-set_local-value\" (func 62))
      (export \"as-load-operand\" (func 63))
      (elem (i32.const 0) 0 1 2 3 4 5 6 7 10 8 11 9 35 36 43 44 45 46 47 12 13 14 15 37 38 39 40 41 42))
    ";
    let wasm_binary = wat2wasm(module_str.as_bytes()).expect("WAST not valid or malformed");
    instantiate(wasm_binary, ImportObject::new()).expect("WASM can't be instantiated")
}

// Line 379
#[test]
fn call_indirect_l379_assert_return_invoke_type_i32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("type-i32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(&vm_context);
        assert_eq!(result, 306 as i32);
    })
    .expect("Error while invoking");
}

// Line 380
#[test]
fn call_indirect_l380_assert_return_invoke_type_i64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("type-i64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(&vm_context);
        assert_eq!(result, 356 as i64);
    })
    .expect("Error while invoking");
}

// Line 381
#[test]
fn call_indirect_l381_assert_return_invoke_type_f32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("type-f32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> f32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(&vm_context);
        assert_eq!(result, 3890.0 as f32);
    })
    .expect("Error while invoking");
}

// Line 382
#[test]
fn call_indirect_l382_assert_return_invoke_type_f64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("type-f64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> f64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(&vm_context);
        assert_eq!(result, 3940.0 as f64);
    })
    .expect("Error while invoking");
}

// Line 384
#[test]
fn call_indirect_l384_assert_return_invoke_type_index() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("type-index") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(&vm_context);
        assert_eq!(result, 100 as i64);
    })
    .expect("Error while invoking");
}

// Line 386
#[test]
fn call_indirect_l386_assert_return_invoke_type_first_i32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("type-first-i32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(&vm_context);
        assert_eq!(result, 32 as i32);
    })
    .expect("Error while invoking");
}

// Line 387
#[test]
fn call_indirect_l387_assert_return_invoke_type_first_i64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("type-first-i64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(&vm_context);
        assert_eq!(result, 64 as i64);
    })
    .expect("Error while invoking");
}

// Line 388
#[test]
fn call_indirect_l388_assert_return_invoke_type_first_f32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("type-first-f32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> f32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(&vm_context);
        assert_eq!(result, 1.32 as f32);
    })
    .expect("Error while invoking");
}

// Line 389
#[test]
fn call_indirect_l389_assert_return_invoke_type_first_f64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("type-first-f64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> f64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(&vm_context);
        assert_eq!(result, 1.64 as f64);
    })
    .expect("Error while invoking");
}

// Line 391
#[test]
fn call_indirect_l391_assert_return_invoke_type_second_i32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("type-second-i32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(&vm_context);
        assert_eq!(result, 32 as i32);
    })
    .expect("Error while invoking");
}

// Line 392
#[test]
fn call_indirect_l392_assert_return_invoke_type_second_i64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("type-second-i64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(&vm_context);
        assert_eq!(result, 64 as i64);
    })
    .expect("Error while invoking");
}

// Line 393
#[test]
fn call_indirect_l393_assert_return_invoke_type_second_f32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("type-second-f32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> f32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(&vm_context);
        assert_eq!(result, 32.0 as f32);
    })
    .expect("Error while invoking");
}

// Line 394
#[test]
fn call_indirect_l394_assert_return_invoke_type_second_f64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("type-second-f64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> f64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(&vm_context);
        assert_eq!(result, 64.1 as f64);
    })
    .expect("Error while invoking");
}

// Line 396
#[test]
fn call_indirect_l396_assert_return_invoke_dispatch() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("dispatch") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, i64, &VmCtx) -> i64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(5 as i32, 2 as i64, &vm_context);
        assert_eq!(result, 2 as i64);
    })
    .expect("Error while invoking");
}

// Line 397
#[test]
fn call_indirect_l397_assert_return_invoke_dispatch() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("dispatch") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, i64, &VmCtx) -> i64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(5 as i32, 5 as i64, &vm_context);
        assert_eq!(result, 5 as i64);
    })
    .expect("Error while invoking");
}

// Line 398
#[test]
fn call_indirect_l398_assert_return_invoke_dispatch() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("dispatch") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, i64, &VmCtx) -> i64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(12 as i32, 5 as i64, &vm_context);
        assert_eq!(result, 120 as i64);
    })
    .expect("Error while invoking");
}

// Line 399
#[test]
fn call_indirect_l399_assert_return_invoke_dispatch() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("dispatch") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, i64, &VmCtx) -> i64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(13 as i32, 5 as i64, &vm_context);
        assert_eq!(result, 8 as i64);
    })
    .expect("Error while invoking");
}

// Line 400
#[test]
fn call_indirect_l400_assert_return_invoke_dispatch() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("dispatch") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, i64, &VmCtx) -> i64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(20 as i32, 2 as i64, &vm_context);
        assert_eq!(result, 2 as i64);
    })
    .expect("Error while invoking");
}

// Line 401

// Line 402

// Line 403

// Line 404

// Line 405

// Line 407
#[test]
fn call_indirect_l407_assert_return_invoke_dispatch_structural_i64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("dispatch-structural-i64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> i64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(5 as i32, &vm_context);
        assert_eq!(result, 9 as i64);
    })
    .expect("Error while invoking");
}

// Line 408
#[test]
fn call_indirect_l408_assert_return_invoke_dispatch_structural_i64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("dispatch-structural-i64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> i64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(12 as i32, &vm_context);
        assert_eq!(result, 362880 as i64);
    })
    .expect("Error while invoking");
}

// Line 409
#[test]
fn call_indirect_l409_assert_return_invoke_dispatch_structural_i64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("dispatch-structural-i64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> i64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(13 as i32, &vm_context);
        assert_eq!(result, 55 as i64);
    })
    .expect("Error while invoking");
}

// Line 410
#[test]
fn call_indirect_l410_assert_return_invoke_dispatch_structural_i64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("dispatch-structural-i64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> i64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(20 as i32, &vm_context);
        assert_eq!(result, 9 as i64);
    })
    .expect("Error while invoking");
}

// Line 411

// Line 412

// Line 414
#[test]
fn call_indirect_l414_assert_return_invoke_dispatch_structural_i32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("dispatch-structural-i32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(4 as i32, &vm_context);
        assert_eq!(result, 9 as i32);
    })
    .expect("Error while invoking");
}

// Line 415
#[test]
fn call_indirect_l415_assert_return_invoke_dispatch_structural_i32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("dispatch-structural-i32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(23 as i32, &vm_context);
        assert_eq!(result, 362880 as i32);
    })
    .expect("Error while invoking");
}

// Line 416
#[test]
fn call_indirect_l416_assert_return_invoke_dispatch_structural_i32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("dispatch-structural-i32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(26 as i32, &vm_context);
        assert_eq!(result, 55 as i32);
    })
    .expect("Error while invoking");
}

// Line 417
#[test]
fn call_indirect_l417_assert_return_invoke_dispatch_structural_i32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("dispatch-structural-i32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(19 as i32, &vm_context);
        assert_eq!(result, 9 as i32);
    })
    .expect("Error while invoking");
}

// Line 418

// Line 419

// Line 421
#[test]
fn call_indirect_l421_assert_return_invoke_dispatch_structural_f32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("dispatch-structural-f32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> f32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(6 as i32, &vm_context);
        assert_eq!(result, 9.0 as f32);
    })
    .expect("Error while invoking");
}

// Line 422
#[test]
fn call_indirect_l422_assert_return_invoke_dispatch_structural_f32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("dispatch-structural-f32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> f32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(24 as i32, &vm_context);
        assert_eq!(result, 362880.0 as f32);
    })
    .expect("Error while invoking");
}

// Line 423
#[test]
fn call_indirect_l423_assert_return_invoke_dispatch_structural_f32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("dispatch-structural-f32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> f32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(27 as i32, &vm_context);
        assert_eq!(result, 55.0 as f32);
    })
    .expect("Error while invoking");
}

// Line 424
#[test]
fn call_indirect_l424_assert_return_invoke_dispatch_structural_f32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("dispatch-structural-f32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> f32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(21 as i32, &vm_context);
        assert_eq!(result, 9.0 as f32);
    })
    .expect("Error while invoking");
}

// Line 425

// Line 426

// Line 428
#[test]
fn call_indirect_l428_assert_return_invoke_dispatch_structural_f64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("dispatch-structural-f64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> f64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(7 as i32, &vm_context);
        assert_eq!(result, 9.0 as f64);
    })
    .expect("Error while invoking");
}

// Line 429
#[test]
fn call_indirect_l429_assert_return_invoke_dispatch_structural_f64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("dispatch-structural-f64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> f64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(25 as i32, &vm_context);
        assert_eq!(result, 362880.0 as f64);
    })
    .expect("Error while invoking");
}

// Line 430
#[test]
fn call_indirect_l430_assert_return_invoke_dispatch_structural_f64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("dispatch-structural-f64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> f64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(28 as i32, &vm_context);
        assert_eq!(result, 55.0 as f64);
    })
    .expect("Error while invoking");
}

// Line 431
#[test]
fn call_indirect_l431_assert_return_invoke_dispatch_structural_f64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("dispatch-structural-f64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> f64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(22 as i32, &vm_context);
        assert_eq!(result, 9.0 as f64);
    })
    .expect("Error while invoking");
}

// Line 432

// Line 433

// Line 435
#[test]
fn call_indirect_l435_assert_return_invoke_fac_i64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fac-i64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i64, &VmCtx) -> i64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(0 as i64, &vm_context);
        assert_eq!(result, 1 as i64);
    })
    .expect("Error while invoking");
}

// Line 436
#[test]
fn call_indirect_l436_assert_return_invoke_fac_i64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fac-i64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i64, &VmCtx) -> i64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(1 as i64, &vm_context);
        assert_eq!(result, 1 as i64);
    })
    .expect("Error while invoking");
}

// Line 437
#[test]
fn call_indirect_l437_assert_return_invoke_fac_i64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fac-i64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i64, &VmCtx) -> i64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(5 as i64, &vm_context);
        assert_eq!(result, 120 as i64);
    })
    .expect("Error while invoking");
}

// Line 438
#[test]
fn call_indirect_l438_assert_return_invoke_fac_i64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fac-i64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i64, &VmCtx) -> i64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(25 as i64, &vm_context);
        assert_eq!(result, 7034535277573963776 as i64);
    })
    .expect("Error while invoking");
}

// Line 440
#[test]
fn call_indirect_l440_assert_return_invoke_fac_i32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fac-i32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(0 as i32, &vm_context);
        assert_eq!(result, 1 as i32);
    })
    .expect("Error while invoking");
}

// Line 441
#[test]
fn call_indirect_l441_assert_return_invoke_fac_i32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fac-i32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(1 as i32, &vm_context);
        assert_eq!(result, 1 as i32);
    })
    .expect("Error while invoking");
}

// Line 442
#[test]
fn call_indirect_l442_assert_return_invoke_fac_i32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fac-i32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(5 as i32, &vm_context);
        assert_eq!(result, 120 as i32);
    })
    .expect("Error while invoking");
}

// Line 443
#[test]
fn call_indirect_l443_assert_return_invoke_fac_i32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fac-i32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(10 as i32, &vm_context);
        assert_eq!(result, 3628800 as i32);
    })
    .expect("Error while invoking");
}

// Line 445
#[test]
fn call_indirect_l445_assert_return_invoke_fac_f32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fac-f32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(f32, &VmCtx) -> f32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(0.0 as f32, &vm_context);
        assert_eq!(result, 1.0 as f32);
    })
    .expect("Error while invoking");
}

// Line 446
#[test]
fn call_indirect_l446_assert_return_invoke_fac_f32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fac-f32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(f32, &VmCtx) -> f32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(1.0 as f32, &vm_context);
        assert_eq!(result, 1.0 as f32);
    })
    .expect("Error while invoking");
}

// Line 447
#[test]
fn call_indirect_l447_assert_return_invoke_fac_f32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fac-f32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(f32, &VmCtx) -> f32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(5.0 as f32, &vm_context);
        assert_eq!(result, 120.0 as f32);
    })
    .expect("Error while invoking");
}

// Line 448
#[test]
fn call_indirect_l448_assert_return_invoke_fac_f32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fac-f32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(f32, &VmCtx) -> f32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(10.0 as f32, &vm_context);
        assert_eq!(result, 3628800.0 as f32);
    })
    .expect("Error while invoking");
}

// Line 450
#[test]
fn call_indirect_l450_assert_return_invoke_fac_f64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fac-f64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(f64, &VmCtx) -> f64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(0.0 as f64, &vm_context);
        assert_eq!(result, 1.0 as f64);
    })
    .expect("Error while invoking");
}

// Line 451
#[test]
fn call_indirect_l451_assert_return_invoke_fac_f64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fac-f64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(f64, &VmCtx) -> f64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(1.0 as f64, &vm_context);
        assert_eq!(result, 1.0 as f64);
    })
    .expect("Error while invoking");
}

// Line 452
#[test]
fn call_indirect_l452_assert_return_invoke_fac_f64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fac-f64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(f64, &VmCtx) -> f64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(5.0 as f64, &vm_context);
        assert_eq!(result, 120.0 as f64);
    })
    .expect("Error while invoking");
}

// Line 453
#[test]
fn call_indirect_l453_assert_return_invoke_fac_f64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fac-f64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(f64, &VmCtx) -> f64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(10.0 as f64, &vm_context);
        assert_eq!(result, 3628800.0 as f64);
    })
    .expect("Error while invoking");
}

// Line 455
#[test]
fn call_indirect_l455_assert_return_invoke_fib_i64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fib-i64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i64, &VmCtx) -> i64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(0 as i64, &vm_context);
        assert_eq!(result, 1 as i64);
    })
    .expect("Error while invoking");
}

// Line 456
#[test]
fn call_indirect_l456_assert_return_invoke_fib_i64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fib-i64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i64, &VmCtx) -> i64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(1 as i64, &vm_context);
        assert_eq!(result, 1 as i64);
    })
    .expect("Error while invoking");
}

// Line 457
#[test]
fn call_indirect_l457_assert_return_invoke_fib_i64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fib-i64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i64, &VmCtx) -> i64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(2 as i64, &vm_context);
        assert_eq!(result, 2 as i64);
    })
    .expect("Error while invoking");
}

// Line 458
#[test]
fn call_indirect_l458_assert_return_invoke_fib_i64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fib-i64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i64, &VmCtx) -> i64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(5 as i64, &vm_context);
        assert_eq!(result, 8 as i64);
    })
    .expect("Error while invoking");
}

// Line 459
#[test]
fn call_indirect_l459_assert_return_invoke_fib_i64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fib-i64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i64, &VmCtx) -> i64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(20 as i64, &vm_context);
        assert_eq!(result, 10946 as i64);
    })
    .expect("Error while invoking");
}

// Line 461
#[test]
fn call_indirect_l461_assert_return_invoke_fib_i32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fib-i32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(0 as i32, &vm_context);
        assert_eq!(result, 1 as i32);
    })
    .expect("Error while invoking");
}

// Line 462
#[test]
fn call_indirect_l462_assert_return_invoke_fib_i32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fib-i32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(1 as i32, &vm_context);
        assert_eq!(result, 1 as i32);
    })
    .expect("Error while invoking");
}

// Line 463
#[test]
fn call_indirect_l463_assert_return_invoke_fib_i32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fib-i32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(2 as i32, &vm_context);
        assert_eq!(result, 2 as i32);
    })
    .expect("Error while invoking");
}

// Line 464
#[test]
fn call_indirect_l464_assert_return_invoke_fib_i32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fib-i32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(5 as i32, &vm_context);
        assert_eq!(result, 8 as i32);
    })
    .expect("Error while invoking");
}

// Line 465
#[test]
fn call_indirect_l465_assert_return_invoke_fib_i32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fib-i32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(20 as i32, &vm_context);
        assert_eq!(result, 10946 as i32);
    })
    .expect("Error while invoking");
}

// Line 467
#[test]
fn call_indirect_l467_assert_return_invoke_fib_f32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fib-f32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(f32, &VmCtx) -> f32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(0.0 as f32, &vm_context);
        assert_eq!(result, 1.0 as f32);
    })
    .expect("Error while invoking");
}

// Line 468
#[test]
fn call_indirect_l468_assert_return_invoke_fib_f32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fib-f32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(f32, &VmCtx) -> f32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(1.0 as f32, &vm_context);
        assert_eq!(result, 1.0 as f32);
    })
    .expect("Error while invoking");
}

// Line 469
#[test]
fn call_indirect_l469_assert_return_invoke_fib_f32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fib-f32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(f32, &VmCtx) -> f32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(2.0 as f32, &vm_context);
        assert_eq!(result, 2.0 as f32);
    })
    .expect("Error while invoking");
}

// Line 470
#[test]
fn call_indirect_l470_assert_return_invoke_fib_f32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fib-f32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(f32, &VmCtx) -> f32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(5.0 as f32, &vm_context);
        assert_eq!(result, 8.0 as f32);
    })
    .expect("Error while invoking");
}

// Line 471
#[test]
fn call_indirect_l471_assert_return_invoke_fib_f32() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fib-f32") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(f32, &VmCtx) -> f32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(20.0 as f32, &vm_context);
        assert_eq!(result, 10946.0 as f32);
    })
    .expect("Error while invoking");
}

// Line 473
#[test]
fn call_indirect_l473_assert_return_invoke_fib_f64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fib-f64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(f64, &VmCtx) -> f64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(0.0 as f64, &vm_context);
        assert_eq!(result, 1.0 as f64);
    })
    .expect("Error while invoking");
}

// Line 474
#[test]
fn call_indirect_l474_assert_return_invoke_fib_f64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fib-f64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(f64, &VmCtx) -> f64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(1.0 as f64, &vm_context);
        assert_eq!(result, 1.0 as f64);
    })
    .expect("Error while invoking");
}

// Line 475
#[test]
fn call_indirect_l475_assert_return_invoke_fib_f64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fib-f64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(f64, &VmCtx) -> f64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(2.0 as f64, &vm_context);
        assert_eq!(result, 2.0 as f64);
    })
    .expect("Error while invoking");
}

// Line 476
#[test]
fn call_indirect_l476_assert_return_invoke_fib_f64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fib-f64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(f64, &VmCtx) -> f64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(5.0 as f64, &vm_context);
        assert_eq!(result, 8.0 as f64);
    })
    .expect("Error while invoking");
}

// Line 477
#[test]
fn call_indirect_l477_assert_return_invoke_fib_f64() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("fib-f64") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(f64, &VmCtx) -> f64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(20.0 as f64, &vm_context);
        assert_eq!(result, 10946.0 as f64);
    })
    .expect("Error while invoking");
}

// Line 479
#[test]
fn call_indirect_l479_assert_return_invoke_even() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("even") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(0 as i32, &vm_context);
        assert_eq!(result, 44 as i32);
    })
    .expect("Error while invoking");
}

// Line 480
#[test]
fn call_indirect_l480_assert_return_invoke_even() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("even") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(1 as i32, &vm_context);
        assert_eq!(result, 99 as i32);
    })
    .expect("Error while invoking");
}

// Line 481
#[test]
fn call_indirect_l481_assert_return_invoke_even() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("even") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(100 as i32, &vm_context);
        assert_eq!(result, 44 as i32);
    })
    .expect("Error while invoking");
}

// Line 482
#[test]
fn call_indirect_l482_assert_return_invoke_even() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("even") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(77 as i32, &vm_context);
        assert_eq!(result, 99 as i32);
    })
    .expect("Error while invoking");
}

// Line 483
#[test]
fn call_indirect_l483_assert_return_invoke_odd() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("odd") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(0 as i32, &vm_context);
        assert_eq!(result, 99 as i32);
    })
    .expect("Error while invoking");
}

// Line 484
#[test]
fn call_indirect_l484_assert_return_invoke_odd() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("odd") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(1 as i32, &vm_context);
        assert_eq!(result, 44 as i32);
    })
    .expect("Error while invoking");
}

// Line 485
#[test]
fn call_indirect_l485_assert_return_invoke_odd() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("odd") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(200 as i32, &vm_context);
        assert_eq!(result, 99 as i32);
    })
    .expect("Error while invoking");
}

// Line 486
#[test]
fn call_indirect_l486_assert_return_invoke_odd() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("odd") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(i32, &VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(77 as i32, &vm_context);
        assert_eq!(result, 44 as i32);
    })
    .expect("Error while invoking");
}

// Line 488

// Line 489

// Line 491
#[test]
fn call_indirect_l491_assert_return_invoke_as_select_first() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("as-select-first") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(&vm_context);
        assert_eq!(result, 306 as i32);
    })
    .expect("Error while invoking");
}

// Line 492
#[test]
fn call_indirect_l492_assert_return_invoke_as_select_mid() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("as-select-mid") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(&vm_context);
        assert_eq!(result, 2 as i32);
    })
    .expect("Error while invoking");
}

// Line 493
#[test]
fn call_indirect_l493_assert_return_invoke_as_select_last() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("as-select-last") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(&vm_context);
        assert_eq!(result, 2 as i32);
    })
    .expect("Error while invoking");
}

// Line 495
#[test]
fn call_indirect_l495_assert_return_invoke_as_if_condition() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("as-if-condition") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(&vm_context);
        assert_eq!(result, 1 as i32);
    })
    .expect("Error while invoking");
}

// Line 497
#[test]
fn call_indirect_l497_assert_return_invoke_as_br_if_first() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("as-br_if-first") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(&vm_context);
        assert_eq!(result, 356 as i64);
    })
    .expect("Error while invoking");
}

// Line 498
#[test]
fn call_indirect_l498_assert_return_invoke_as_br_if_last() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("as-br_if-last") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(&vm_context);
        assert_eq!(result, 2 as i32);
    })
    .expect("Error while invoking");
}

// Line 500
#[test]
fn call_indirect_l500_assert_return_invoke_as_br_table_first() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("as-br_table-first") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> f32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(&vm_context);
        assert_eq!(result, 3890.0 as f32);
    })
    .expect("Error while invoking");
}

// Line 501
#[test]
fn call_indirect_l501_assert_return_invoke_as_br_table_last() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("as-br_table-last") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(&vm_context);
        assert_eq!(result, 2 as i32);
    })
    .expect("Error while invoking");
}

// Line 503
#[test]
fn call_indirect_l503_assert_return_invoke_as_store_first() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("as-store-first") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(&vm_context);
        assert_eq!(result, ());
    })
    .expect("Error while invoking");
}

// Line 504
#[test]
fn call_indirect_l504_assert_return_invoke_as_store_last() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("as-store-last") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(&vm_context);
        assert_eq!(result, ());
    })
    .expect("Error while invoking");
}

// Line 506
#[test]
fn call_indirect_l506_assert_return_invoke_as_memory_grow_value() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("as-memory.grow-value") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(&vm_context);
        assert_eq!(result, 1 as i32);
    })
    .expect("Error while invoking");
}

// Line 507
#[test]
fn call_indirect_l507_assert_return_invoke_as_return_value() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("as-return-value") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(&vm_context);
        assert_eq!(result, 1 as i32);
    })
    .expect("Error while invoking");
}

// Line 508
#[test]
fn call_indirect_l508_assert_return_invoke_as_drop_operand() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("as-drop-operand") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(&vm_context);
        assert_eq!(result, ());
    })
    .expect("Error while invoking");
}

// Line 509
#[test]
fn call_indirect_l509_assert_return_invoke_as_br_value() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("as-br-value") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> f32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(&vm_context);
        assert_eq!(result, 1.0 as f32);
    })
    .expect("Error while invoking");
}

// Line 510
#[test]
fn call_indirect_l510_assert_return_invoke_as_set_local_value() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("as-set_local-value") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> f64 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(&vm_context);
        assert_eq!(result, 1.0 as f64);
    })
    .expect("Error while invoking");
}

// Line 511
#[test]
fn call_indirect_l511_assert_return_invoke_as_load_operand() {
    let ResultObject {
        mut instance,
        module,
    } = create_module_1();
    let func_index = match module.info.exports.get("as-load-operand") {
        Some(&Export::Function(index)) => index,
        _ => panic!("Function not found"),
    };
    let invoke_fn: fn(&VmCtx) -> i32 = get_instance_function!(instance, func_index);
    let vm_context = instance.generate_context();
    panic::catch_unwind(|| {
        let result = invoke_fn(&vm_context);
        assert_eq!(result, 1 as i32);
    })
    .expect("Error while invoking");
}

// Line 516

#[test]
fn call_indirect_l516_assert_malformed() {
    let wasm_binary = [
        40, 116, 121, 112, 101, 32, 36, 115, 105, 103, 32, 40, 102, 117, 110, 99, 32, 40, 112, 97,
        114, 97, 109, 32, 105, 51, 50, 41, 32, 40, 114, 101, 115, 117, 108, 116, 32, 105, 51, 50,
        41, 41, 41, 40, 116, 97, 98, 108, 101, 32, 48, 32, 97, 110, 121, 102, 117, 110, 99, 41, 40,
        102, 117, 110, 99, 32, 40, 114, 101, 115, 117, 108, 116, 32, 105, 51, 50, 41, 32, 32, 40,
        99, 97, 108, 108, 95, 105, 110, 100, 105, 114, 101, 99, 116, 32, 40, 116, 121, 112, 101,
        32, 36, 115, 105, 103, 41, 32, 40, 114, 101, 115, 117, 108, 116, 32, 105, 51, 50, 41, 32,
        40, 112, 97, 114, 97, 109, 32, 105, 51, 50, 41, 32, 32, 32, 32, 40, 105, 51, 50, 46, 99,
        111, 110, 115, 116, 32, 48, 41, 32, 40, 105, 51, 50, 46, 99, 111, 110, 115, 116, 32, 48,
        41, 32, 32, 41, 41,
    ];
    let compilation = compile(wasm_binary.to_vec());
    assert!(
        compilation.is_err(),
        "WASM should not compile as is malformed"
    );
}

// Line 528

#[test]
fn call_indirect_l528_assert_malformed() {
    let wasm_binary = [
        40, 116, 121, 112, 101, 32, 36, 115, 105, 103, 32, 40, 102, 117, 110, 99, 32, 40, 112, 97,
        114, 97, 109, 32, 105, 51, 50, 41, 32, 40, 114, 101, 115, 117, 108, 116, 32, 105, 51, 50,
        41, 41, 41, 40, 116, 97, 98, 108, 101, 32, 48, 32, 97, 110, 121, 102, 117, 110, 99, 41, 40,
        102, 117, 110, 99, 32, 40, 114, 101, 115, 117, 108, 116, 32, 105, 51, 50, 41, 32, 32, 40,
        99, 97, 108, 108, 95, 105, 110, 100, 105, 114, 101, 99, 116, 32, 40, 112, 97, 114, 97, 109,
        32, 105, 51, 50, 41, 32, 40, 116, 121, 112, 101, 32, 36, 115, 105, 103, 41, 32, 40, 114,
        101, 115, 117, 108, 116, 32, 105, 51, 50, 41, 32, 32, 32, 32, 40, 105, 51, 50, 46, 99, 111,
        110, 115, 116, 32, 48, 41, 32, 40, 105, 51, 50, 46, 99, 111, 110, 115, 116, 32, 48, 41, 32,
        32, 41, 41,
    ];
    let compilation = compile(wasm_binary.to_vec());
    assert!(
        compilation.is_err(),
        "WASM should not compile as is malformed"
    );
}

// Line 540

#[test]
fn call_indirect_l540_assert_malformed() {
    let wasm_binary = [
        40, 116, 121, 112, 101, 32, 36, 115, 105, 103, 32, 40, 102, 117, 110, 99, 32, 40, 112, 97,
        114, 97, 109, 32, 105, 51, 50, 41, 32, 40, 114, 101, 115, 117, 108, 116, 32, 105, 51, 50,
        41, 41, 41, 40, 116, 97, 98, 108, 101, 32, 48, 32, 97, 110, 121, 102, 117, 110, 99, 41, 40,
        102, 117, 110, 99, 32, 40, 114, 101, 115, 117, 108, 116, 32, 105, 51, 50, 41, 32, 32, 40,
        99, 97, 108, 108, 95, 105, 110, 100, 105, 114, 101, 99, 116, 32, 40, 112, 97, 114, 97, 109,
        32, 105, 51, 50, 41, 32, 40, 114, 101, 115, 117, 108, 116, 32, 105, 51, 50, 41, 32, 40,
        116, 121, 112, 101, 32, 36, 115, 105, 103, 41, 32, 32, 32, 32, 40, 105, 51, 50, 46, 99,
        111, 110, 115, 116, 32, 48, 41, 32, 40, 105, 51, 50, 46, 99, 111, 110, 115, 116, 32, 48,
        41, 32, 32, 41, 41,
    ];
    let compilation = compile(wasm_binary.to_vec());
    assert!(
        compilation.is_err(),
        "WASM should not compile as is malformed"
    );
}

// Line 552

#[test]
fn call_indirect_l552_assert_malformed() {
    let wasm_binary = [
        40, 116, 121, 112, 101, 32, 36, 115, 105, 103, 32, 40, 102, 117, 110, 99, 32, 40, 112, 97,
        114, 97, 109, 32, 105, 51, 50, 41, 32, 40, 114, 101, 115, 117, 108, 116, 32, 105, 51, 50,
        41, 41, 41, 40, 116, 97, 98, 108, 101, 32, 48, 32, 97, 110, 121, 102, 117, 110, 99, 41, 40,
        102, 117, 110, 99, 32, 40, 114, 101, 115, 117, 108, 116, 32, 105, 51, 50, 41, 32, 32, 40,
        99, 97, 108, 108, 95, 105, 110, 100, 105, 114, 101, 99, 116, 32, 40, 114, 101, 115, 117,
        108, 116, 32, 105, 51, 50, 41, 32, 40, 116, 121, 112, 101, 32, 36, 115, 105, 103, 41, 32,
        40, 112, 97, 114, 97, 109, 32, 105, 51, 50, 41, 32, 32, 32, 32, 40, 105, 51, 50, 46, 99,
        111, 110, 115, 116, 32, 48, 41, 32, 40, 105, 51, 50, 46, 99, 111, 110, 115, 116, 32, 48,
        41, 32, 32, 41, 41,
    ];
    let compilation = compile(wasm_binary.to_vec());
    assert!(
        compilation.is_err(),
        "WASM should not compile as is malformed"
    );
}

// Line 564

#[test]
fn call_indirect_l564_assert_malformed() {
    let wasm_binary = [
        40, 116, 121, 112, 101, 32, 36, 115, 105, 103, 32, 40, 102, 117, 110, 99, 32, 40, 112, 97,
        114, 97, 109, 32, 105, 51, 50, 41, 32, 40, 114, 101, 115, 117, 108, 116, 32, 105, 51, 50,
        41, 41, 41, 40, 116, 97, 98, 108, 101, 32, 48, 32, 97, 110, 121, 102, 117, 110, 99, 41, 40,
        102, 117, 110, 99, 32, 40, 114, 101, 115, 117, 108, 116, 32, 105, 51, 50, 41, 32, 32, 40,
        99, 97, 108, 108, 95, 105, 110, 100, 105, 114, 101, 99, 116, 32, 40, 114, 101, 115, 117,
        108, 116, 32, 105, 51, 50, 41, 32, 40, 112, 97, 114, 97, 109, 32, 105, 51, 50, 41, 32, 40,
        116, 121, 112, 101, 32, 36, 115, 105, 103, 41, 32, 32, 32, 32, 40, 105, 51, 50, 46, 99,
        111, 110, 115, 116, 32, 48, 41, 32, 40, 105, 51, 50, 46, 99, 111, 110, 115, 116, 32, 48,
        41, 32, 32, 41, 41,
    ];
    let compilation = compile(wasm_binary.to_vec());
    assert!(
        compilation.is_err(),
        "WASM should not compile as is malformed"
    );
}

// Line 576

#[test]
fn call_indirect_l576_assert_malformed() {
    let wasm_binary = [
        40, 116, 97, 98, 108, 101, 32, 48, 32, 97, 110, 121, 102, 117, 110, 99, 41, 40, 102, 117,
        110, 99, 32, 40, 114, 101, 115, 117, 108, 116, 32, 105, 51, 50, 41, 32, 32, 40, 99, 97,
        108, 108, 95, 105, 110, 100, 105, 114, 101, 99, 116, 32, 40, 114, 101, 115, 117, 108, 116,
        32, 105, 51, 50, 41, 32, 40, 112, 97, 114, 97, 109, 32, 105, 51, 50, 41, 32, 40, 105, 51,
        50, 46, 99, 111, 110, 115, 116, 32, 48, 41, 32, 40, 105, 51, 50, 46, 99, 111, 110, 115,
        116, 32, 48, 41, 41, 41,
    ];
    let compilation = compile(wasm_binary.to_vec());
    assert!(
        compilation.is_err(),
        "WASM should not compile as is malformed"
    );
}

// Line 586

#[test]
fn call_indirect_l586_assert_malformed() {
    let wasm_binary = [
        40, 116, 97, 98, 108, 101, 32, 48, 32, 97, 110, 121, 102, 117, 110, 99, 41, 40, 102, 117,
        110, 99, 32, 40, 99, 97, 108, 108, 95, 105, 110, 100, 105, 114, 101, 99, 116, 32, 40, 112,
        97, 114, 97, 109, 32, 36, 120, 32, 105, 51, 50, 41, 32, 40, 105, 51, 50, 46, 99, 111, 110,
        115, 116, 32, 48, 41, 32, 40, 105, 51, 50, 46, 99, 111, 110, 115, 116, 32, 48, 41, 41, 41,
    ];
    let compilation = compile(wasm_binary.to_vec());
    assert!(
        compilation.is_err(),
        "WASM should not compile as is malformed"
    );
}

// Line 593

#[test]
fn call_indirect_l593_assert_malformed() {
    let wasm_binary = [
        40, 116, 121, 112, 101, 32, 36, 115, 105, 103, 32, 40, 102, 117, 110, 99, 41, 41, 40, 116,
        97, 98, 108, 101, 32, 48, 32, 97, 110, 121, 102, 117, 110, 99, 41, 40, 102, 117, 110, 99,
        32, 40, 114, 101, 115, 117, 108, 116, 32, 105, 51, 50, 41, 32, 32, 40, 99, 97, 108, 108,
        95, 105, 110, 100, 105, 114, 101, 99, 116, 32, 40, 116, 121, 112, 101, 32, 36, 115, 105,
        103, 41, 32, 40, 114, 101, 115, 117, 108, 116, 32, 105, 51, 50, 41, 32, 40, 105, 51, 50,
        46, 99, 111, 110, 115, 116, 32, 48, 41, 41, 41,
    ];
    let compilation = compile(wasm_binary.to_vec());
    assert!(
        compilation.is_err(),
        "WASM should not compile as is malformed"
    );
}

// Line 603

#[test]
fn call_indirect_l603_assert_malformed() {
    let wasm_binary = [
        40, 116, 121, 112, 101, 32, 36, 115, 105, 103, 32, 40, 102, 117, 110, 99, 32, 40, 112, 97,
        114, 97, 109, 32, 105, 51, 50, 41, 32, 40, 114, 101, 115, 117, 108, 116, 32, 105, 51, 50,
        41, 41, 41, 40, 116, 97, 98, 108, 101, 32, 48, 32, 97, 110, 121, 102, 117, 110, 99, 41, 40,
        102, 117, 110, 99, 32, 40, 114, 101, 115, 117, 108, 116, 32, 105, 51, 50, 41, 32, 32, 40,
        99, 97, 108, 108, 95, 105, 110, 100, 105, 114, 101, 99, 116, 32, 40, 116, 121, 112, 101,
        32, 36, 115, 105, 103, 41, 32, 40, 114, 101, 115, 117, 108, 116, 32, 105, 51, 50, 41, 32,
        40, 105, 51, 50, 46, 99, 111, 110, 115, 116, 32, 48, 41, 41, 41,
    ];
    let compilation = compile(wasm_binary.to_vec());
    assert!(
        compilation.is_err(),
        "WASM should not compile as is malformed"
    );
}

// Line 613

#[test]
fn call_indirect_l613_assert_malformed() {
    let wasm_binary = [
        40, 116, 121, 112, 101, 32, 36, 115, 105, 103, 32, 40, 102, 117, 110, 99, 32, 40, 112, 97,
        114, 97, 109, 32, 105, 51, 50, 41, 32, 40, 114, 101, 115, 117, 108, 116, 32, 105, 51, 50,
        41, 41, 41, 40, 116, 97, 98, 108, 101, 32, 48, 32, 97, 110, 121, 102, 117, 110, 99, 41, 40,
        102, 117, 110, 99, 32, 32, 40, 99, 97, 108, 108, 95, 105, 110, 100, 105, 114, 101, 99, 116,
        32, 40, 116, 121, 112, 101, 32, 36, 115, 105, 103, 41, 32, 40, 112, 97, 114, 97, 109, 32,
        105, 51, 50, 41, 32, 40, 105, 51, 50, 46, 99, 111, 110, 115, 116, 32, 48, 41, 32, 40, 105,
        51, 50, 46, 99, 111, 110, 115, 116, 32, 48, 41, 41, 41,
    ];
    let compilation = compile(wasm_binary.to_vec());
    assert!(
        compilation.is_err(),
        "WASM should not compile as is malformed"
    );
}

// Line 623

#[test]
fn call_indirect_l623_assert_malformed() {
    let wasm_binary = [
        40, 116, 121, 112, 101, 32, 36, 115, 105, 103, 32, 40, 102, 117, 110, 99, 32, 40, 112, 97,
        114, 97, 109, 32, 105, 51, 50, 32, 105, 51, 50, 41, 32, 40, 114, 101, 115, 117, 108, 116,
        32, 105, 51, 50, 41, 41, 41, 40, 116, 97, 98, 108, 101, 32, 48, 32, 97, 110, 121, 102, 117,
        110, 99, 41, 40, 102, 117, 110, 99, 32, 40, 114, 101, 115, 117, 108, 116, 32, 105, 51, 50,
        41, 32, 32, 40, 99, 97, 108, 108, 95, 105, 110, 100, 105, 114, 101, 99, 116, 32, 40, 116,
        121, 112, 101, 32, 36, 115, 105, 103, 41, 32, 40, 112, 97, 114, 97, 109, 32, 105, 51, 50,
        41, 32, 40, 114, 101, 115, 117, 108, 116, 32, 105, 51, 50, 41, 32, 32, 32, 32, 40, 105, 51,
        50, 46, 99, 111, 110, 115, 116, 32, 48, 41, 32, 40, 105, 51, 50, 46, 99, 111, 110, 115,
        116, 32, 48, 41, 32, 32, 41, 41,
    ];
    let compilation = compile(wasm_binary.to_vec());
    assert!(
        compilation.is_err(),
        "WASM should not compile as is malformed"
    );
}

// Line 638

#[test]
fn call_indirect_l638_assert_invalid() {
    let wasm_binary = [
        0, 97, 115, 109, 1, 0, 0, 0, 1, 4, 1, 96, 0, 0, 3, 2, 1, 0, 10, 9, 1, 7, 0, 65, 0, 17, 0,
        0, 11,
    ];
    let compilation = compile(wasm_binary.to_vec());
    assert!(
        compilation.is_err(),
        "WASM should not compile as is invalid"
    );
}

// Line 646

#[test]
fn call_indirect_l646_assert_invalid() {
    let wasm_binary = [
        0, 97, 115, 109, 1, 0, 0, 0, 1, 4, 1, 96, 0, 0, 3, 2, 1, 0, 4, 4, 1, 112, 0, 0, 10, 10, 1,
        8, 0, 65, 0, 17, 0, 0, 69, 11,
    ];
    let compilation = compile(wasm_binary.to_vec());
    assert!(
        compilation.is_err(),
        "WASM should not compile as is invalid"
    );
}

// Line 654

#[test]
fn call_indirect_l654_assert_invalid() {
    let wasm_binary = [
        0, 97, 115, 109, 1, 0, 0, 0, 1, 8, 2, 96, 0, 1, 126, 96, 0, 0, 3, 2, 1, 1, 4, 4, 1, 112, 0,
        0, 10, 10, 1, 8, 0, 65, 0, 17, 0, 0, 69, 11,
    ];
    let compilation = compile(wasm_binary.to_vec());
    assert!(
        compilation.is_err(),
        "WASM should not compile as is invalid"
    );
}

// Line 663

#[test]
fn call_indirect_l663_assert_invalid() {
    let wasm_binary = [
        0, 97, 115, 109, 1, 0, 0, 0, 1, 8, 2, 96, 1, 127, 0, 96, 0, 0, 3, 2, 1, 1, 4, 4, 1, 112, 0,
        0, 10, 9, 1, 7, 0, 65, 0, 17, 0, 0, 11,
    ];
    let compilation = compile(wasm_binary.to_vec());
    assert!(
        compilation.is_err(),
        "WASM should not compile as is invalid"
    );
}

// Line 671

#[test]
fn call_indirect_l671_assert_invalid() {
    let wasm_binary = [
        0, 97, 115, 109, 1, 0, 0, 0, 1, 9, 2, 96, 2, 124, 127, 0, 96, 0, 0, 3, 2, 1, 1, 4, 4, 1,
        112, 0, 0, 10, 9, 1, 7, 0, 65, 0, 17, 0, 0, 11,
    ];
    let compilation = compile(wasm_binary.to_vec());
    assert!(
        compilation.is_err(),
        "WASM should not compile as is invalid"
    );
}

// Line 679

#[test]
fn call_indirect_l679_assert_invalid() {
    let wasm_binary = [
        0, 97, 115, 109, 1, 0, 0, 0, 1, 4, 1, 96, 0, 0, 3, 2, 1, 0, 4, 4, 1, 112, 0, 0, 10, 11, 1,
        9, 0, 65, 1, 65, 0, 17, 0, 0, 11,
    ];
    let compilation = compile(wasm_binary.to_vec());
    assert!(
        compilation.is_err(),
        "WASM should not compile as is invalid"
    );
}

// Line 687

#[test]
fn call_indirect_l687_assert_invalid() {
    let wasm_binary = [
        0, 97, 115, 109, 1, 0, 0, 0, 1, 4, 1, 96, 0, 0, 3, 2, 1, 0, 4, 4, 1, 112, 0, 0, 10, 20, 1,
        18, 0, 68, 0, 0, 0, 0, 0, 0, 0, 64, 65, 1, 65, 0, 17, 0, 0, 11,
    ];
    let compilation = compile(wasm_binary.to_vec());
    assert!(
        compilation.is_err(),
        "WASM should not compile as is invalid"
    );
}

// Line 698

#[test]
fn call_indirect_l698_assert_invalid() {
    let wasm_binary = [
        0, 97, 115, 109, 1, 0, 0, 0, 1, 8, 2, 96, 1, 127, 0, 96, 0, 0, 3, 2, 1, 1, 4, 4, 1, 112, 0,
        0, 10, 10, 1, 8, 0, 65, 1, 1, 17, 0, 0, 11,
    ];
    let compilation = compile(wasm_binary.to_vec());
    assert!(
        compilation.is_err(),
        "WASM should not compile as is invalid"
    );
}

// Line 706

#[test]
fn call_indirect_l706_assert_invalid() {
    let wasm_binary = [
        0, 97, 115, 109, 1, 0, 0, 0, 1, 8, 2, 96, 1, 127, 0, 96, 0, 0, 3, 2, 1, 1, 4, 4, 1, 112, 0,
        0, 10, 11, 1, 9, 0, 65, 0, 66, 1, 17, 0, 0, 11,
    ];
    let compilation = compile(wasm_binary.to_vec());
    assert!(
        compilation.is_err(),
        "WASM should not compile as is invalid"
    );
}

// Line 715

#[test]
fn call_indirect_l715_assert_invalid() {
    let wasm_binary = [
        0, 97, 115, 109, 1, 0, 0, 0, 1, 9, 2, 96, 2, 127, 127, 0, 96, 0, 0, 3, 2, 1, 1, 4, 4, 1,
        112, 0, 0, 10, 12, 1, 10, 0, 1, 65, 1, 65, 0, 17, 0, 0, 11,
    ];
    let compilation = compile(wasm_binary.to_vec());
    assert!(
        compilation.is_err(),
        "WASM should not compile as is invalid"
    );
}

// Line 725

#[test]
fn call_indirect_l725_assert_invalid() {
    let wasm_binary = [
        0, 97, 115, 109, 1, 0, 0, 0, 1, 9, 2, 96, 2, 127, 127, 0, 96, 0, 0, 3, 2, 1, 1, 4, 4, 1,
        112, 0, 0, 10, 12, 1, 10, 0, 65, 1, 1, 65, 0, 17, 0, 0, 11,
    ];
    let compilation = compile(wasm_binary.to_vec());
    assert!(
        compilation.is_err(),
        "WASM should not compile as is invalid"
    );
}

// Line 735

#[test]
fn call_indirect_l735_assert_invalid() {
    let wasm_binary = [
        0, 97, 115, 109, 1, 0, 0, 0, 1, 9, 2, 96, 2, 127, 124, 0, 96, 0, 0, 3, 2, 1, 1, 4, 4, 1,
        112, 0, 0, 10, 20, 1, 18, 0, 68, 0, 0, 0, 0, 0, 0, 240, 63, 65, 1, 65, 0, 17, 0, 0, 11,
    ];
    let compilation = compile(wasm_binary.to_vec());
    assert!(
        compilation.is_err(),
        "WASM should not compile as is invalid"
    );
}

// Line 745

#[test]
fn call_indirect_l745_assert_invalid() {
    let wasm_binary = [
        0, 97, 115, 109, 1, 0, 0, 0, 1, 9, 2, 96, 2, 124, 127, 0, 96, 0, 0, 3, 2, 1, 1, 4, 4, 1,
        112, 0, 0, 10, 20, 1, 18, 0, 65, 1, 68, 0, 0, 0, 0, 0, 0, 240, 63, 65, 0, 17, 0, 0, 11,
    ];
    let compilation = compile(wasm_binary.to_vec());
    assert!(
        compilation.is_err(),
        "WASM should not compile as is invalid"
    );
}

// Line 759

#[test]
fn call_indirect_l759_assert_invalid() {
    let wasm_binary = [
        0, 97, 115, 109, 1, 0, 0, 0, 1, 4, 1, 96, 0, 0, 3, 2, 1, 0, 4, 4, 1, 112, 0, 0, 10, 9, 1,
        7, 0, 65, 0, 17, 1, 0, 11,
    ];
    let compilation = compile(wasm_binary.to_vec());
    assert!(
        compilation.is_err(),
        "WASM should not compile as is invalid"
    );
}

// Line 766

#[test]
fn call_indirect_l766_assert_invalid() {
    let wasm_binary = [
        0, 97, 115, 109, 1, 0, 0, 0, 1, 4, 1, 96, 0, 0, 3, 2, 1, 0, 4, 4, 1, 112, 0, 0, 10, 13, 1,
        11, 0, 65, 0, 17, 148, 152, 219, 226, 3, 0, 11,
    ];
    let compilation = compile(wasm_binary.to_vec());
    assert!(
        compilation.is_err(),
        "WASM should not compile as is invalid"
    );
}

// Line 777

#[test]
fn call_indirect_l777_assert_invalid() {
    let wasm_binary = [
        0, 97, 115, 109, 1, 0, 0, 0, 4, 5, 1, 112, 1, 2, 2, 9, 8, 1, 0, 65, 0, 11, 2, 0, 0,
    ];
    let compilation = compile(wasm_binary.to_vec());
    assert!(
        compilation.is_err(),
        "WASM should not compile as is invalid"
    );
}
